### ISSUE TITLE
Cannot read property 'declareTemporary' of null

### ISSUE THREAD

**Issue by kevin-coyle** [jakearchibald/offline-wikipedia#1]
Getting the following when I run `npm run serve` or `gulp serve`

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: /Users/kevincoyle/development/offline-wikipedia/index.js: Cannot read property 'declareTemporary' of null
    at getOuterFnExpr (/Users/kevincoyle/development/offline-wikipedia/node_modules/regenerator/lib/visit.js:279:35)
    at Context.types.PathVisitor.fromMethodsObject.visitFunction (/Users/kevincoyle/development/offline-wikipedia/node_modules/regenerator/lib/visit.js:108:23)
    at Context.invokeVisitorMethod (/Users/kevincoyle/development/offline-wikipedia/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:306:43)
    at Visitor.PVp.visitWithoutReset (/Users/kevincoyle/development/offline-wikipedia/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:180:28)
    at NodePath.each (/Users/kevincoyle/development/offline-wikipedia/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path.js:96:22)
    at visitChildren (/Users/kevincoyle/development/offline-wikipedia/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:199:14)
    at Visitor.PVp.visitWithoutReset (/Users/kevincoyle/development/offline-wikipedia/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at visitChildren (/Users/kevincoyle/development/offline-wikipedia/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:226:21)
    at Visitor.PVp.visitWithoutReset (/Users/kevincoyle/development/offline-wikipedia/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at visitChildren (/Users/kevincoyle/development/offline-wikipedia/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:226:21)

```

**Comment by gs-akhan** [comment]
Same issue here as well.  
Tried every possible way. It fails one way or another.. :(

**Comment by richardgrey** [comment]
Same issue

**Comment by mathiasbynens** [comment]
Same issue. I randomly tried using a couple of different Regenerator versions to no avail.

**Comment by armoucar** [comment]
Same :-1: 

@jakearchibald do you know why is that happening?

**Comment by jakearchibald** [comment]
Thanks for the nudge. I hate that "not watching" is git's default. Looking into it.

**Comment by jakearchibald** [comment]
Yeah ok, I can recreate this. Lemmie find out which dependency has gone mad (or which one I was misusing).

**Comment by bluebeckie** [comment]
hmmm, checked that version is updated:
npm ls | grep regenerator
├─┬ regenerator@0.8.31
still have the same error from my side...

**Comment by jakearchibald** [comment]
oh ffs. Yeeep. This is becoming a bit of a heisenbug.

**Comment by jakearchibald** [comment]
Babel was doing something weird with their dependencies. Fixed with some awful hackery.

**Comment by bluebeckie** [comment]
works now. thx!!

**Comment by armoucar** [comment]
:+1:
